### ISSUE TITLE
Configure automatic backup of ikiwiki-newton_knowledge_base repository

### ISSUE THREAD

**Issue by morgant** [UNNA/ikiwiki-newton_knowledge_base#1]
Now that this repository is live on GitHub, I need to configure automatic mirroring/backup of the ikiwiki-newton_knowledge_base repository. I'll start with a mirror on the makkintosshu backups server using https://github.com/morgant/tiggit/.

**Comment by morgant** [comment]
I have configured an automatic mirror on my backup server.

**Comment by splorp** [comment]
I had a feeling that’s what you were going to use Tiggit for. Nice.

**Comment by splorp** [comment]
Oops. Didn’t mean to reopen this.
